{{- if and .Values.persistencedb.enabled (not .Values.persistencedb.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hdp.fullname" . }}-psql
  labels:
    app: {{ template "hdp.fullname" . }}-psql
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistencedb.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistencedb.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistencedb.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistencedb.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
