apiVersion: v1
kind: Service
metadata:
  name: {{ template "hdp.fullname" . }}-hbase-master
  labels:
    app: {{ template "hdp.name" . }}-hbase-master
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - name: hbasemasterui
    port: 16010
    targetPort: 16010
  - name: "16000"
    port: 16000
    targetPort: 16000
  # - name: thrift
  #   port: 9090
  #   targetPort: 9090
  # - name: thriftinfo
  #   port: 9095
  #   targetPort: 9095
  selector:
    app: {{ template "hdp.name" . }}-hbase-master
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
