{{- if and .Values.persistencedb.enabled (not .Values.persistencedb.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hdp.fullname" . }}-zoodata
  labels:
    app: {{ template "hdp.fullname" . }}-zoodata
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistencedb.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistencedb.sizezoo | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistencedb.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistencedb.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
#
# ---
#
# {{- if and .Values.persistencedb.enabled (not .Values.persistencedb.existingClaim) }}
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: {{ template "hdp.fullname" . }}-zoologs
#   labels:
#     app: {{ template "hdp.fullname" . }}-zoologs
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   accessModes:
#     - {{ .Values.persistencedb.accessMode | quote }}
#   resources:
#     requests:
#       storage: {{ .Values.persistencedb.sizezoo | quote }}
# {{- if .Values.persistence.storageClass }}
# {{- if (eq "-" .Values.persistencedb.storageClass) }}
#   storageClassName: ""
# {{- else }}
#   storageClassName: "{{ .Values.persistencedb.storageClass }}"
# {{- end }}
# {{- end }}
# {{- end }}
