apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "hdp.fullname" . }}-hive-server
  labels:
    app: {{ template "hdp.name" . }}-hive-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdp.name" . }}-hive-server
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - env:
        - name: CORE_CONF_fs_defaultFS
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_fs_defaultFS
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: CORE_CONF_hadoop_http_staticuser_user
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_hadoop_http_staticuser_user
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_hadoop_proxyuser_hue_groups
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_hadoop_proxyuser_hue_hosts
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HDFS_CONF_dfs_permissions_enabled
          valueFrom:
            configMapKeyRef:
              key: HDFS_CONF_dfs_permissions_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HDFS_CONF_dfs_webhdfs_enabled
          valueFrom:
            configMapKeyRef:
              key: HDFS_CONF_dfs_webhdfs_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_datanucleus_autoCreateSchema
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_datanucleus_autoCreateSchema
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_hive_metastore_uris
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_hive_metastore_uris
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionURL
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_javax_jdo_option_ConnectionURL
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName
          valueFrom:
            configMapKeyRef:
              key: HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_log___aggregation___enable
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_log___aggregation___enable
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_log_server_url
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_log_server_url
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_nodemanager_remote___app___log___dir
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_nodemanager_remote___app___log___dir
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_address
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_address
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_fs_state___store_uri
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_fs_state___store_uri
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_hostname
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_hostname
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_recovery_enabled
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_recovery_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_resource__tracker_address
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_resource__tracker_address
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_scheduler_address
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_scheduler_address
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_store_class
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_store_class
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_timeline___service_enabled
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_timeline___service_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_timeline___service_generic___application___history_enabled
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_timeline___service_generic___application___history_enabled
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        - name: YARN_CONF_yarn_timeline___service_hostname
          valueFrom:
            configMapKeyRef:
              key: YARN_CONF_yarn_timeline___service_hostname
              name: {{ template "hdp.fullname" . }}-hive-metastore-hadoop-hive-env
        image: 190742198407.dkr.ecr.us-west-2.amazonaws.com/xl/hdp:hivev1.2 #1.1
        imagePullPolicy: "IfNotPresent"
        name: hive-server
        ports:
        - containerPort: 10000
        - containerPort: 10002
        livenessProbe:
          exec:
            command:
            - nc # ['nc', '-vz', '{{ template "hdp.fullname" . }}-hdfs-nn-0.{{ template "hdp.fullname" . }}-hdfs-nn', '9000']
            - -vz
            - {{ template "hdp.fullname" . }}-hdfs-nn-0.{{ template "hdp.fullname" . }}-hdfs-nn
            - "9000"
          initialDelaySeconds: 2
          failureThreshold: 1
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - name: hadoop-config
          mountPath: /usr/hdp/2.6.3.0-235/hadoop/etc/hadoop
      volumes:
      - name: hadoop-config
        configMap:
          name: {{ template "hdp.fullname" . }}
      restartPolicy: Always
