apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "hdp.fullname" . }}-hive-metastore-postgresql
  labels:
    app: {{ template "hdp.name" . }}-hive-metastore-postgresql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdp.name" . }}-hive-metastore-postgresql
        release: {{ .Release.Name }}
    spec:
      hostname: {{ template "hdp.fullname" . }}-hive-metastore-postgresql
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgresql
        image: 190742198407.dkr.ecr.us-west-2.amazonaws.com/xl/hdp:hivepsqlv1.5 #1.4
        imagePullPolicy: "IfNotPresent"
        resources: {}
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            value: hive
        volumeMounts:
        - name: hivedata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: hivedata
        persistentVolumeClaim:
          claimName: {{ template "hdp.fullname" . }}-psql
      restartPolicy: Always
status: {}
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: 1Gi
          #   requests:
          #    cpu: "500m"
          #    memory: 512Mi
