zeppelin:
  image: dylanmei/zeppelin:0.7.2 #dr.xenon.team/public_utils/zeppelin:v2 #

resources:
  limits:
   cpu: "2000m"
   memory: "4096Mi"
  requests:
   cpu: "2000m"
   memory: "4096Mi"

  initialDelaySeconds: 20
  timeoutSeconds: 1
hadoop:
  useConfigMap: false
  configMapName: hadoop-hadoop  #name of hadoop configMap
  configPath: /usr/hadoop-2.7.3/etc/hadoop  #path where hadoop config is mounted

spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2

persistence:
  enabled: true  #enable true if you want pvc
  storageClass: block2
  accessMode: ReadWriteOnce
  zeppelinDataSize: 4Gi
  zeppelinConfDataSize: 1Gi

ingress:
   enabled: false
   annotations:
     kubernetes.io/ingress.class: traefik
     traefik.frontend.rule.type: PathPrefixStrip
   domainName: neuron-labs.stpi.in

   tls: []
    # - secretName: zeppelin-tls-secret
    #   hosts: zeppelin.local

# nodeSelector: {}
#   kops.k8s.io/xyzgroup: nodes
