apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: softwares
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "zeppelin.name" . }}
        release: {{ .Release.Name }}
        type: softwares
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: zeppelin
          image: {{ .Values.zeppelin.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_JAVA_OPTS
              value: >-
                -Dspark.driver.memory={{ .Values.spark.driverMemory }}
                -Dspark.executor.memory={{ .Values.spark.executorMemory }}
{{- if .Values.hadoop.useConfigMap }}
            - name: MASTER
              value: "yarn"
            - name: SPARK_SUBMIT_OPTIONS
              value: >-
                --deploy-mode client
                --num-executors {{ .Values.spark.numExecutors }}
{{- end }}
          volumeMounts:
            - name: zeppelin-conf
              mountPath: /usr/zeppelin/conf
            - mountPath: /usr/zeppelin/notebook
              name: zeppelin-workdir
{{- if .Values.hadoop.useConfigMap }}
            - mountPath: {{ .Values.hadoop.configPath }}
              name: hadoop-config
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            #initialDelaySeconds: {{ .Values.zeppelin.initialDelaySeconds }}
            #timeoutSeconds: {{ .Values.zeppelin.timeoutSeconds }}
      volumes:
        - name: zeppelin-conf
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-conf-zeppelin
        - name: zeppelin-workdir
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-zeppelin
{{- if .Values.hadoop.useConfigMap }}
        - name: hadoop-config
          configMap:
            name: {{ .Values.hadoop.configMapName }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
