{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "zeppelin.fullname" . }}-ing
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  # {{- with .Values.ingress.annotations }}
  # annotations:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  # tls:
  #   - hosts:
  #     - {{ .Release.Name }}.{{ .Values.ingress.domainName}}
  #     secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Release.Name }}.{{ .Values.ingress.domainName}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "zeppelin.fullname" . }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
