{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "zeppelin.fullname" . }}-ing
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - www.{{ .Release.Name }}.{{ .Values.ingress.domainName}}
      - {{ .Release.Name }}.{{ .Values.ingress.domainName}}
      secretName: {{ .Release.Name }}-secret
  rules:
    - host: www.{{ .Release.Name }}.{{ .Values.ingress.domainName}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "zeppelin.fullname" . }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
