jupyter:
  image: 801204773696.dkr.ecr.ap-south-1.amazonaws.com/sl/jupyternotebook
  imageTag: v1.2
  imagePullPolicy: "IfNotPresent"

password: "stacklabs"

persistence:
  enabled: true
  storageClass: gp2
  accessMode: ReadWriteOnce
  size: 1Gi
securityContext:
  fsgroup: 1000
nodeSelector:
  kops.k8s.io/instancegroup: nodes

service:
  type: ClusterIP
  port: "8888"

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "500Mi"
    cpu: "300m"

ingress:
   enabled: true
   annotations:
     kubernetes.io/ingress.class: traefik
     traefik.frontend.rule.type: PathPrefixStrip
   domainName: stacklabs.co
