apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oozie
  labels:
    app: {{ template "bigdata.name" . }}-oozie
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bigdata.name" . }}-oozie
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: oozie
          image: {{ .Values.oozie.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 11000
              name: httpoozie
            - containerPort: 11001
              name: back
          env:
            - name: HDFS
              value: hdfs://{{ template "bigdata.fullname" . }}-hdfs-nn:9000/
            - name: HDFSSVC
              value: {{ template "bigdata.fullname" . }}-hdfs-nn
