apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bigdata.fullname" . }}-hbase-thrift
  labels:
    app: {{ template "bigdata.name" . }}-hbase-thrift
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bigdata.name" . }}-hbase-thrift
        release: {{ .Release.Name }}
    spec:
      hostname: {{ template "bigdata.fullname" . }}-hbase-thrift
      terminationGracePeriodSeconds: 0
      containers:
        - name: hbasemaster
          image: 190742198407.dkr.ecr.us-west-2.amazonaws.com/xl/spark:hbasethriftv2
          imagePullPolicy: "IfNotPresent"
          env:
          - name: HBASE_CONF_hbase_cluster_distributed
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_cluster_distributed
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_master
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_master
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_master_hostname
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_master_hostname
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_master_info_port
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_master_info_port
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_master_port
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_master_port
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_regionserver_info_port
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_regionserver_info_port
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_regionserver_port
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_regionserver_port
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_rootdir
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_rootdir
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_CONF_hbase_zookeeper_quorum
            valueFrom:
              configMapKeyRef:
                key: HBASE_CONF_hbase_zookeeper_quorum
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: HBASE_MANAGES_ZK
            valueFrom:
              configMapKeyRef:
                key: HBASE_MANAGES_ZK
                name: {{ template "bigdata.fullname" . }}-hbase-master-hbase-distributed-local-env
          - name: SERVICE_PRECONDITION
            value: "{{ template "bigdata.fullname" . }}-hdfs-nn:50070 {{ template "bigdata.fullname" . }}-hdfs-dn:50075 {{ .Release.Name }}-zookeeper:2181"
          - name: HBASE_CONF_hbase_regionserver_hostname
            value: {{ template "bigdata.fullname" . }}-hbase-region # hbase-region
          - name: HBASE_CONF_hbase_regionserver
            value: {{ template "bigdata.fullname" . }}-hbase-region:16020 #  hbase-region:16020
          livenessProbe:
            exec:
              command:
              - nc # ['nc', '-vz', '{{ template "bigdata.fullname" . }}-hdfs-nn-0.{{ template "bigdata.fullname" . }}-hdfs-nn', '9000']
              - -vz
              - {{ template "bigdata.fullname" . }}-hdfs-nn-0.{{ template "bigdata.fullname" . }}-hdfs-nn
              - "9000"
            initialDelaySeconds: 2
            failureThreshold: 1
            periodSeconds: 2
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - nc # ['nc', '-vz', '{{ template "bigdata.fullname" . }}-hdfs-nn-0.{{ template "bigdata.fullname" . }}-hdfs-nn', '9000']
              - -vz
              - {{ template "bigdata.fullname" . }}-hbase-master
              - "16000"
            initialDelaySeconds: 2
            failureThreshold: 1
            periodSeconds: 2
            timeoutSeconds: 1
          ports:
          - containerPort: 16010
          - containerPort: 16000
          - containerPort: 9090
          - containerPort: 9095
      restartPolicy: Always
status: {}
