apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bigdata.fullname" . }}-hive-metastore-postgresql
  labels:
    app: {{ template "bigdata.name" . }}-hive-metastore-postgresql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bigdata.name" . }}-hive-metastore-postgresql
        release: {{ .Release.Name }}
    spec:
      hostname: {{ template "bigdata.fullname" . }}-hive-metastore-postgresql
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgresql
        image: {{ .Values.hive.imagepsql }} #bde2020/hive-metastore-postgresql:2.3.0
        imagePullPolicy: "IfNotPresent"
        resources: {}
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
            name: psql
        volumeMounts:
        - name: hivedata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: hivedata
        persistentVolumeClaim:
          claimName: {{ template "bigdata.fullname" . }}-psql
      restartPolicy: Always
status: {}
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: 1Gi
          #   requests:
          #    cpu: "500m"
          #    memory: 512Mi
