apiVersion: v1
kind: Service
metadata:
  name: {{ template "bigdata.fullname" . }}-hbase-region
  labels:
    app: {{ template "bigdata.name" . }}-hbase-region
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - name: hbaseregionui
    port: 16030
    targetPort: 16030
  - name: "16020"
    port: 16020
    targetPort: 16020
  selector:
    app: {{ template "bigdata.name" . }}-hbase-region
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
