type: softwares
workspace_id: nl-123
user_id: nlu-123
user_name: nlu

# Default values for superset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

## Set default image, imageTag, and imagePullPolicy.
image:
  repository: "apache/superset"
  tag: "dockerize"
  pullPolicy: "IfNotPresent"

initFile: |-
  /usr/local/bin/superset-init --username $USERNAME --firstname admin --lastname user --email admin@superset.com --password $USER_PASSWORD
  superset runserver

configFile: |-
  #---------------------------------------------------------
  # Superset specific config
  #---------------------------------------------------------
  ROW_LIMIT = 5000
  SUPERSET_WORKERS = 2

  SUPERSET_WEBSERVER_PORT = 8088
  #---------------------------------------------------------

  #---------------------------------------------------------
  # Flask App Builder configuration
  #---------------------------------------------------------
  # Your App secret key
  SECRET_KEY = '\2\1thisismyscretkey\1\2\e\y\y\h'

  # The SQLAlchemy connection string to your database backend
  # This connection defines the path to the database that stores your
  # superset metadata (slices, connections, tables, dashboards, ...).
  # Note that the connection information to connect to the datasources
  # you want to explore are managed directly in the web UI
  SQLALCHEMY_DATABASE_URI = 'sqlite:////var/lib/superset/superset.db'


  # Flask-WTF flag for CSRF
  WTF_CSRF_ENABLED = True
  # Add endpoints that need to be exempt from CSRF protection
  WTF_CSRF_EXEMPT_LIST = []

  # Set this API key to enable Mapbox visualizations
  MAPBOX_API_KEY = ''

## Extra environment variables that will be passed onto deployment pod
##
extraEnv: {}

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for secret keys, etc
##
extraEnvFromSecret: ""

auth:
  username: superset
  password: superset#
  email: admin@superset.com
  firstname: admin
  lastname: user

persistence:

  ## If true, superset server will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
  enabled: true

  ## superset data Persistent Volume access modes
  ## Must match those of existing PV or dynamic provisioner
  ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  accessModes:
    - ReadWriteOnce

  ## superset data Persistent Volume size
  ##
  size: 8Gi

  ## superset server data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "5000m"
    memory: "7000Mi"
  requests:
    cpu: "2000m"
    memory: "5000Mi"

## Expose the superset service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  type: ClusterIP
  port: 8088

ingress:
  ## If true, superset Ingress will be created
  ##
  enabled: true
  className: traefik
  domainName: neuralcompany.team
  secretName: neuralcompany.team
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  ## superset Ingress hostnames
  ## Must be provided if Ingress is enabled
  ##

  ## superset Ingress path
  ## Optional, allows specifying paths for more flexibility
  ## E.g. Traefik ingress likes paths
  ##
  path: /

labels:
  app.kubernetes.io/name: superset
  app.kubernetes.io/instance: apache-superset
  app.kubernetes.io/version: 0.24.0
  app.kubernetes.io/managed-by: helm-charts
  app.kubernetes.io/contact: rajat
  app.kubernetes.io/workload: apache-superset
  app.kubernetes.io/env: prod
  app.kubernetes.io/tier: data-visualization
  app.kubernetes.io/project: neuronlabs
  app.kubernetes.io/requested-by: na

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##

# nodeSelector:
#   magnum.openstack.org/nodegroup: nl-software

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
tolerations: []

## Affinity and anti-affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##

## Configure liveness/readiness params
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
##
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 600
  timeoutSeconds: 120
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 600
  timeoutSeconds: 120
  periodSeconds: 10
  failureThreshold: 3
